### ISSUE TITLE
Undefined miniver version

### ISSUE THREAD

**Issue by akhmerov** [jbweston/miniver#8]
Following the instructions from the readme on current master (abe5a59) results in the following:

```bash
curl https://raw.githubusercontent.com/jbweston/miniver/master/install-miniver | python - . 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5280  100  5280    0     0  23677      0 --:--:-- --:--:-- --:--:-- 23677
Traceback (most recent call last):
  File "<stdin>", line 170, in <module>
  File "<stdin>", line 134, in main
  File "<stdin>", line 127, in get_args
NameError: name '_miniver_version' is not defined
```

**Comment by jbweston** [comment]
Works for me?

```
curl https://raw.githubusercontent.com/jbweston/miniver/abe5a59/install-miniver | python - yolo 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5280  100  5280    0     0  25384      0 --:--:-- --:--:-- --:--:-- 25507
Miniver is installed into 'yolo/'. You still have to copy the
following snippet into your 'setup.py':

    # Loads version.py module without importing the whole package.
    def get_version_and_cmdclass(package_path):
        import os
        from importlib.util import module_from_spec, spec_from_file_location
        spec = spec_from_file_location('version',
                                       os.path.join(package_path, '_version.py'))
        module = module_from_spec(spec)
        spec.loader.exec_module(module)
        return module.__version__, module.cmdclass


    version, cmdclass = get_version_and_cmdclass('yolo')

    setup(
        ...,
        version=version,
        cmdclass=cmdclass,
    )

```
